apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mjxiaf40q-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mjxiaf40q-dotnet-basic-gitops